spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MailDataProcessingDB
    username: postgres
    password: HeLLCaT2113
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation : true
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/MailDataProcessingDB
    password: HeLLCaT2113
    user: postgres
    locations: classpath:db/migration
server:
  port: 8091

