spring:
  datasource:
    url: jdbc:h2:mem:MailDataProcessingDB
    username: eror
    password: 123321
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8090

