spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data/MailDataProcessingDB
    username: eror
    password: 123321
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    url: jdbc:h2:tcp://localhost/~/data/MailDataProcessingDB
    password: 123321
    user: eror
    locations: classpath:h2/migration
server:
  port: 8091

